version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: ../.env
    volumes:
      - ..:/TarkovTracker:cached
    networks:
      - TarkovTracker
    ports:
      - "3000:3000"
networks:
  TarkovTracker:
    name: TarkovTracker

